package com.dfj.similan.domain;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mobile
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.country
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.countrycode
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    private String countrycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.city
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.postcode
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    private String postcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.fname
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    private String fname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.lname
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    private String lname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.named
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    private String named;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.telephone
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ctime
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    private String ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.findpasscode
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    private String findpasscode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.findpasscodeendtime
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    private String findpasscodeendtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mobile
     *
     * @return the value of user.mobile
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mobile
     *
     * @param mobile the value for user.mobile
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.country
     *
     * @return the value of user.country
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.country
     *
     * @param country the value for user.country
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.countrycode
     *
     * @return the value of user.countrycode
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    public String getCountrycode() {
        return countrycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.countrycode
     *
     * @param countrycode the value for user.countrycode
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    public void setCountrycode(String countrycode) {
        this.countrycode = countrycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.city
     *
     * @return the value of user.city
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.city
     *
     * @param city the value for user.city
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.postcode
     *
     * @return the value of user.postcode
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.postcode
     *
     * @param postcode the value for user.postcode
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.fname
     *
     * @return the value of user.fname
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    public String getFname() {
        return fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.fname
     *
     * @param fname the value for user.fname
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    public void setFname(String fname) {
        this.fname = fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.lname
     *
     * @return the value of user.lname
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    public String getLname() {
        return lname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.lname
     *
     * @param lname the value for user.lname
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    public void setLname(String lname) {
        this.lname = lname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.named
     *
     * @return the value of user.named
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    public String getNamed() {
        return named;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.named
     *
     * @param named the value for user.named
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    public void setNamed(String named) {
        this.named = named;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.telephone
     *
     * @return the value of user.telephone
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.telephone
     *
     * @param telephone the value for user.telephone
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ctime
     *
     * @return the value of user.ctime
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    public String getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ctime
     *
     * @param ctime the value for user.ctime
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    public void setCtime(String ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.findpasscode
     *
     * @return the value of user.findpasscode
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    public String getFindpasscode() {
        return findpasscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.findpasscode
     *
     * @param findpasscode the value for user.findpasscode
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    public void setFindpasscode(String findpasscode) {
        this.findpasscode = findpasscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.findpasscodeendtime
     *
     * @return the value of user.findpasscodeendtime
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    public String getFindpasscodeendtime() {
        return findpasscodeendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.findpasscodeendtime
     *
     * @param findpasscodeendtime the value for user.findpasscodeendtime
     *
     * @mbggenerated Tue Jan 17 19:41:33 ICT 2017
     */
    public void setFindpasscodeendtime(String findpasscodeendtime) {
        this.findpasscodeendtime = findpasscodeendtime;
    }
}